# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-12 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('vat_rate', models.IntegerField(choices=[(1, 0.23), (2, 0.08), (3, 0.05), (4, 0)])),
                ('stock', models.IntegerField()),
                ('categories', models.ManyToManyField(to='ecommerce.Category')),
            ],
        ),
    ]
