# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-14 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20171214_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='ecommerce.Category'),
        ),
    ]
